#ifndef GRIDBOX_SECRETS_H
#define GRIDBOX_SECRETS_H

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define PROXY_BASE_URL "https://your-domain.example/api/esp"
#define DEVICE_API_KEY "YOUR_DEVICE_API_KEY"
#define STATION_SHORT_CODE "ABCD"
#define STATION_ID "00000000-0000-0000-0000-000000000000"

#endif
